MN-589: utility app
insolar/mainnet pull request #63
Opened 2020-08-13 10:06 UTC by Hirama

**- What I did**
A CLI app for creating an additional deposit in the member's wallet
**- How I did it**

**- How to verify it**

**- Description for the changelog**

2020-08-19 08:14 UTC, pavlushev approved these changes

2020-08-26 12:04 UTC, megge-dream requested changes

2020-08-26 12:04 UTC, megge-dream commented on application/cmd/integrum/README.md
> +        -w, --waitTime int        Milliseconds to wait after each transfer (default 500)
```suggestion
        -w, --waitTime int        Milliseconds to wait after each deposit creation (default 500)
```

2020-08-26 12:04 UTC, megge-dream commented on application/cmd/integrum/README.md
> +        -u, --dbUrl string        URL with credential to the DB
Is it observer db? Its not clear from description

2020-08-26 13:09 UTC, megge-dream approved these changes

2020-08-26 13:34 UTC, uhzxl requested changes
Would be better to extract main logic to somewhere (maybe to another file) cause now it mixed with input parameters processing and makes it difficult to understand

2020-08-26 13:34 UTC, uhzxl commented on application/cmd/integrum/main.go
> +			fmt.Println(rows.RowsAffected())
Looks like the query doesn't work as expected.

When running a query on test data, I got this
![image](https://user-images.githubusercontent.com/19386609/91309065-d4e50900-e7b8-11ea-8348-bb506b6966bb.png)


```suggestion
			err = db.Model().
				Table("deposits").
				Column("deposit_ref", "member_ref").
				Where("status = 'confirmed'").
				Where("eth_hash != 'genesis_deposit'").
				Where("eth_hash != 'genesis_deposit2'").
				Where("eth_hash not like E'%\\_2'").
				Where(`not exists (
					select 1 
					from deposits as inn
					where inn.eth_hash = concat("deposits".eth_hash, '_2')
				)`).
				Select(&members)
			if err != nil {
				panic(err)
			}

			if len(members) == 0 {
				return errors.New("Members without second deposit not found")
			}
			fmt.Println(len(members))
```

2020-08-27 11:17 UTC, uhzxl approved these changes

2020-08-27 14:27 UTC, merged