MN-588: update migration procedure
insolar/mainnet pull request #65
Opened 2020-08-13 12:26 UTC by uhzxl

**- What I did**
Injected linear deposit creation into migration procedure
**- How I did it**

- Added `deposit.createAdditionalDeposit` method that creates linear deposit
- Added call of `createAdditionalDeposit` when enough confirmations have been collected
- Added corresponding test changes to `TestDepositMigration` test to check that additional deposit created and created from "Public Allocation 2" fund
- Skipped `TestDepositCreate` test because it becomes impossible to create test users of the old type (with only one deposit)
- Made changes in `sdk.go` and `launchnet.go` to simulate actual fund reallocation
- And finally made changes in `fund_test.go` according to fund reallocation

**- How to verify it**
Run func tests

**- Description for the changelog**

2020-08-17 10:20 UTC, SergeyRadist commented on application/functest/fund_test.go
> +	_, err = testrequest.SignedRequestWithEmptyRequestRef(t, launchnet.TestRPCUrlPublic, m,
Why we throw out this if statement ?

2020-08-17 10:21 UTC, SergeyRadist commented on application/functest/fund_test.go
> -	if time.Now().Unix() < time.Unix(genesisstate.NetworkIncentivesUnholdStartDate, 0).AddDate(0, lastIdx, 0).Unix() {
Why we throw out this if statement ?

2020-08-19 09:38 UTC, SergeyRadist commented on application/functest/fund_test.go
> -	if time.Now().Unix() < time.Unix(genesisstate.NetworkIncentivesUnholdStartDate, 0).AddDate(0, lastIdx, 0).Unix() {
solved

2020-08-19 09:39 UTC, SergeyRadist approved these changes

2020-08-26 09:14 UTC, Hirama approved these changes

2020-08-26 09:47 UTC, megge-dream requested changes

2020-08-26 09:47 UTC, megge-dream commented on application/functest/test_utils.go
>  		return errors.New(fmt.Sprintf("deposit amount should be %s, current value: %s", expectedBalance, deposit["amount"]))
```suggestion
		return errors.New(fmt.Sprintf("deposit amount should be %s, current value: %s", expectedAmount, deposit["amount"]))
```

2020-08-26 11:46 UTC, megge-dream approved these changes

2020-08-26 13:51 UTC, LinnikD approved these changes

2020-08-26 14:25 UTC, pavlushev approved these changes

2020-08-26 14:43 UTC, dmitry-shidlovsky approved these changes

2020-08-26 14:44 UTC, merged